### ISSUE TITLE
I have found a bug in ToHex function.

### ISSUE THREAD

**Issue by mkornaukhov** [cpeditor/lsp-cpp#2]
Hi! It seems there is a bug: https://github.com/cpeditor/lsp-cpp/blob/master/include/LSPUri.hpp#L100
I suppose the line is going to be `return  ch > 9 ? ch + 65 : ch + 48;`, because 65 (not 55) - is ASCII code for 'A' letter.

**Comment by coder3101** [comment]
Yes this indeed is a bug. However, the library still works because the URI is rarely encoded in hex, unless file path has some very special characters in it.

**Comment by ouuan** [comment]
This was actually fixed in the upstream: https://github.com/alextsao1999/lsp-cpp/commit/6b973f806d0ca7ff0dea6438e1b33a5c5195129b.

We could merge the upstream.

**Comment by ouuan** [comment]
It seems that the upstream changes don't compile by simply copy-pasting. I'll fix this then.
